config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tables
  resources :matches
  resources :partners
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  },
                     path: '',
                     path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/partner.rb
class Partner < ApplicationRecord
    has_and_belongs_to_many :matches
    has_many :users
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_action :set_partner, only: %i[ show edit update destroy ]

  # GET /partners or /partners.json
  def index
    @partners = Partner.all
  end

  # GET /partners/1 or /partners/1.json
  def show
  end

  # GET /partners/new
  def new
    @partner = Partner.new
  end

  # GET /partners/1/edit
  def edit
  end

  # POST /partners or /partners.json
  def create
    @partner = Partner.new(partner_params)

    respond_to do |format|
      if @partner.save
        format.html { redirect_to @partner, notice: "Partner was successfully created." }
        format.json { render :show, status: :created, location: @partner }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partners/1 or /partners/1.json
  def update
    respond_to do |format|
      if @partner.update(partner_params)
        format.html { redirect_to @partner, notice: "Partner was successfully updated." }
        format.json { render :show, status: :ok, location: @partner }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partners/1 or /partners/1.json
  def destroy
    @partner.destroy
    respond_to do |format|
      format.html { redirect_to partners_url, notice: "Partner was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partner
      @partner = Partner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def partner_params
      params.require(:partner).permit(:id_player1, :id_player2, :name)
    end
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/views/partners/_form.html.erb
<%= form_with(model: partner, local: true) do |form| %>
  <% if partner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(partner.errors.count, "error") %> prohibited this partner from being saved:</h2>

      <ul>
      <% partner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id_player1 %>
    <%= form.number_field :id_player1 %>
  </div>

  <div class="field">
    <%= form.label :id_player2 %>
    <%= form.number_field :id_player2 %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/partners/edit.html.erb
<h1>Editing Partner</h1>

<%= render 'form', partner: @partner %>

<%= link_to 'Show', @partner %> |
<%= link_to 'Back', partners_path %>

app/views/partners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Partners</h1>

<table>
  <thead>
    <tr>
      <th>Id player1</th>
      <th>Id player2</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @partners.each do |partner| %>
      <tr>
        <td><%= partner.id_player1 %></td>
        <td><%= partner.id_player2 %></td>
        <td><%= partner.name %></td>
        <td><%= link_to 'Show', partner %></td>
        <td><%= link_to 'Edit', edit_partner_path(partner) %></td>
        <td><%= link_to 'Destroy', partner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Partner', new_partner_path %>

app/views/partners/new.html.erb
<h1>New Partner</h1>

<%= render 'form', partner: @partner %>

<%= link_to 'Back', partners_path %>

app/views/partners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id player1:</strong>
  <%= @partner.id_player1 %>
</p>

<p>
  <strong>Id player2:</strong>
  <%= @partner.id_player2 %>
</p>

<p>
  <strong>Name:</strong>
  <%= @partner.name %>
</p>

<%= link_to 'Edit', edit_partner_path(@partner) %> |
<%= link_to 'Back', partners_path %>