config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tables
  resources :matches
  resources :partners
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  },
                     path: '',
                     path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: %i[ show edit update destroy ]

  # GET /tables or /tables.json
  def index
    @tables = Table.all
  end

  # GET /tables/1 or /tables/1.json
  def show
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables or /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: "Table was successfully created." }
        format.json { render :show, status: :created, location: @table }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1 or /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to @table, notice: "Table was successfully updated." }
        format.json { render :show, status: :ok, location: @table }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1 or /tables/1.json
  def destroy
    @table.destroy
    respond_to do |format|
      format.html { redirect_to tables_url, notice: "Table was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def table_params
      params.require(:table).permit(:name, :win, :played, :loss, :position, :difference)
    end
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_form.html.erb
<%= form_with(model: table, local: true) do |form| %>
  <% if table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
      <% table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :win %>
    <%= form.number_field :win %>
  </div>

  <div class="field">
    <%= form.label :played %>
    <%= form.number_field :played %>
  </div>

  <div class="field">
    <%= form.label :loss %>
    <%= form.number_field :loss %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position %>
  </div>

  <div class="field">
    <%= form.label :difference %>
    <%= form.number_field :difference %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tables/edit.html.erb
<h1>Editing Table</h1>

<%= render 'form', table: @table %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tables</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Win</th>
      <th>Played</th>
      <th>Loss</th>
      <th>Position</th>
      <th>Difference</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tables.each do |table| %>
      <tr>
        <td><%= table.name %></td>
        <td><%= table.win %></td>
        <td><%= table.played %></td>
        <td><%= table.loss %></td>
        <td><%= table.position %></td>
        <td><%= table.difference %></td>
        <td><%= link_to 'Show', table %></td>
        <td><%= link_to 'Edit', edit_table_path(table) %></td>
        <td><%= link_to 'Destroy', table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Table', new_table_path %>

app/views/tables/new.html.erb
<h1>New Table</h1>

<%= render 'form', table: @table %>

<%= link_to 'Back', tables_path %>

app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @table.name %>
</p>

<p>
  <strong>Win:</strong>
  <%= @table.win %>
</p>

<p>
  <strong>Played:</strong>
  <%= @table.played %>
</p>

<p>
  <strong>Loss:</strong>
  <%= @table.loss %>
</p>

<p>
  <strong>Position:</strong>
  <%= @table.position %>
</p>

<p>
  <strong>Difference:</strong>
  <%= @table.difference %>
</p>

<%= link_to 'Edit', edit_table_path(@table) %> |
<%= link_to 'Back', tables_path %>