config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tables
  resources :matches
  resources :partners
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  },
                     path: '',
                     path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord
    has_and_belongs_to_many :partners
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %i[ show edit update destroy ]

  # GET /matches or /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1 or /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches or /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: "Match was successfully created." }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1 or /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: "Match was successfully updated." }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1 or /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: "Match was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_params
      params.require(:match).permit(:state, :set1p1, :set1p2, :set2p1, :set2p2, :set3p1, :set3p2)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_with(model: match, local: true) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :set1p1 %>
    <%= form.number_field :set1p1 %>
  </div>

  <div class="field">
    <%= form.label :set1p2 %>
    <%= form.number_field :set1p2 %>
  </div>

  <div class="field">
    <%= form.label :set2p1 %>
    <%= form.number_field :set2p1 %>
  </div>

  <div class="field">
    <%= form.label :set2p2 %>
    <%= form.number_field :set2p2 %>
  </div>

  <div class="field">
    <%= form.label :set3p1 %>
    <%= form.number_field :set3p1 %>
  </div>

  <div class="field">
    <%= form.label :set3p2 %>
    <%= form.number_field :set3p2 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Matches</h1>

<table>
  <thead>
    <tr>
      <th>State</th>
      <th>Set1p1</th>
      <th>Set1p2</th>
      <th>Set2p1</th>
      <th>Set2p2</th>
      <th>Set3p1</th>
      <th>Set3p2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.state %></td>
        <td><%= match.set1p1 %></td>
        <td><%= match.set1p2 %></td>
        <td><%= match.set2p1 %></td>
        <td><%= match.set2p2 %></td>
        <td><%= match.set3p1 %></td>
        <td><%= match.set3p2 %></td>
        <td><%= link_to 'Show', match %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %></td>
        <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State:</strong>
  <%= @match.state %>
</p>

<p>
  <strong>Set1p1:</strong>
  <%= @match.set1p1 %>
</p>

<p>
  <strong>Set1p2:</strong>
  <%= @match.set1p2 %>
</p>

<p>
  <strong>Set2p1:</strong>
  <%= @match.set2p1 %>
</p>

<p>
  <strong>Set2p2:</strong>
  <%= @match.set2p2 %>
</p>

<p>
  <strong>Set3p1:</strong>
  <%= @match.set3p1 %>
</p>

<p>
  <strong>Set3p2:</strong>
  <%= @match.set3p2 %>
</p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>